import React, {Component} from "react";

const TimeSelect = ({selecetedTime, disableBeforeTime}) => {

    return (
        <> {
            <select>
                <option>12:00am</option>
                <option>12:15am</option>
                <option>12:30am</option>
                <option>12:45am</option>
                <option>1:00am</option>
                <option>1:15am</option>
                <option>1:30am</option>
                <option>1:45am</option>
                <option>2:00am</option>
                <option>2:15am</option>
                <option>2:30am</option>
                <option>2:45am</option>
                <option>3:00am</option>
                <option>3:15am</option>
                <option>3:30am</option>
                <option>3:45am</option>
                <option>4:00am</option>
                <option>4:15am</option>
                <option>4:30am</option>
                <option>4:45am</option>
                <option>5:00am</option>
                <option>5:15am</option>
                <option>5:30am</option>
                <option>5:45am</option>
                <option>6:00am</option>
                <option>6:15am</option>
                <option>6:30am</option>
                <option>6:45am</option>
                <option>7:00am</option>
                <option>7:15am</option>
                <option>7:30am</option>
                <option>7:45am</option>
                <option>8:00am</option>
                <option>8:15am</option>
                <option>8:30am</option>
                <option>8:45am</option>
                <option>9:00am</option>
                <option>9:15am</option>
                <option>9:30am</option>
                <option>9:45am</option>
                <option>10:00am</option>
                <option>10:15am</option>
                <option>10:30am</option>
                <option>10:45am</option>
                <option>11:00am</option>
                <option>11:15am</option>
                <option>11:30am</option>
                <option>11:45am</option>
                <option>12:00pm</option>
                <option>12:15pm</option>
                <option>12:30pm</option>
                <option>12:45pm</option>
                <option>1:15pm</option>
                <option>1:30pm</option>
                <option>1:45pm</option>
                <option>2:00pm</option>
                <option>2:15pm</option>
                <option>2:30pm</option>
                <option>2:45pm</option>
                <option>3:00pm</option>
                <option>3:15pm</option>
                <option>3:30pm</option>
                <option>3:45pm</option>
                <option>4:00pm</option>
                <option>4:15pm</option>
                <option>4:30pm</option>
                <option>4:45pm</option>
                <option>5:00pm</option>
                <option>5:15pm</option>
                <option>5:30pm</option>
                <option>5:45pm</option>
                <option>6:00pm</option>
                <option>6:15pm</option>
                <option>6:30pm</option>
                <option>6:45pm</option>
                <option>7:00pm</option>
                <option>7:15pm</option>
                <option>7:30pm</option>
                <option>7:45pm</option>
                <option>8:00pm</option>
                <option>8:15pm</option>
                <option>8:30pm</option>
                <option>8:45pm</option>
                <option>9:00pm</option>
                <option>9:15pm</option>
                <option>9:30pm</option>
                <option>9:45pm</option>
                <option>10:00pm</option>
                <option>10:15pm</option>
                <option>10:30pm</option>
                <option>10:45pm</option>
                <option>11:00pm</option>
                <option>11:15pm</option>
                <option>11:30pm</option>
                <option>11:45pm</option>
            </select>

        }
        </>
    );
};
        export default TimeSelect;