// sample data to get things started

const sampleEvents = {
    event1: {
        duid: "1",
        summary: "This is an event",
        description: "I am the very model of a modern major general. __________________________________________________________________________",
        dtstart: "2021-10-04T22:30:00",
        dtend: "2021-10-04T23:30:00",
        location: "My house",
        projects: "+project1",
        contexts: "@context @home",
    },
    event2: {
        duid: "2",
        summary: "A second event.",
        description: "I am the very model of a modern major general.",
        dtstart: "2021-10-04T10:00:00",
        dtend: "2021-10-04T11:15:00",
        location: "At work",
        projects: "+someProject +anotherProject",
        contexts: "@work",
    },
    event3: {
        duid: "3",
        summary: "Lunch, no +project",
        description: "Naf Naf grill for lunch.",
        dtstart: "2021-10-04T12:00:00",
        dtend: "2021-10-04T12:45:00",
        location: "Naf Naf grill",
        projects: "",
        contexts: "@personal",
    },
    event4: {
        duid: "4",
        summary: "15 minute thing with no @contexts",
        description: "Sort thing ",
        dtstart: "2021-10-04T14:00:00",
        dtend: "2021-10-04T14:15:00",
        location: "At work",
        projects: "+someProject +anotherProject",
        contexts: "",
    },
    event5: {
        duid: "5",
        summary: "A 30 minute event",
        description: "I am the very model of a modern major general.",
        dtstart: "2021-10-04T14:30:00",
        dtend: "2021-10-04T15:00:00",
        location: "At work",
        projects: "+someProject +anotherProject",
        contexts: "@work",
    },
    event6: {
        duid: "6",
        summary: "This is really early",
        description: "This is an event at 1am so I don't have to scroll.",
        dtstart: "2021-10-04T01:30:00", 
        dtend: "2021-10-04T02:15:00",
        location: "bed",
        projects: "+insomnia",
        contexts: "@home",
    },
    event7: {
        duid: "7",
        summary: "Something",
        description: "This is an event at 1am so I don't have to scroll.",
        dtstart: "2021-10-04T15:00:00", 
        dtend: "2021-10-04T15:15:00",
        location: "bed",
        projects: "+insomnia",
        contexts: "@home",
    },

    event8: {
        duid: "8",
        summary: "Wake up",
        description: "Wake up and make coffee.",
        dtstart: "2021-10-04T06:30:00", 
        dtend: "2021-10-04T06:45:00",
        location: "home",
        projects: "",
        contexts: "@personal",
    },
    event9: {
        duid: "9",
        summary: "Devotions",
        description: "Time in the morning for devotions.",
        dtstart: "2021-10-04T06:45:00", 
        dtend: "2021-10-04T07:15:00",
        location: "home",
        projects: "",
        contexts: "@spiritual",
    },
    event10: {
        duid: "10",
        summary: "Get Ready, multiple @contexts",
        description: "Get ready for work.",
        dtstart: "2021-10-04T07:15:00", 
        dtend: "2021-10-04T08:00:00",
        location: "home",
        projects: "",
        contexts: "@personal @work",
    },
    event11: {
        duid: "11",
        summary: "Status call on Sales Project",
        description: "Status call +meeting @work",
        dtstart: "2021-10-04T08:00:00", 
        dtend: "2021-10-04T09:00:00",
        location: "online",
        projects: "+meeting +project",
        contexts: "@work",
    },
    event12: {
        duid: "12",
        summary: "Responding to email",
        description: "Responding to email",
        dtstart: "2021-10-04T09:00:00", 
        dtend: "2021-10-04T09:30:00",
        location: "online",
        projects: "+email",
        contexts: "@work",
    },
    event13: {
        duid: "13",
        summary: "New Project requirements document",
        description: "Create the requirements document for the new project.",
        dtstart: "2021-10-04T09:30:00", 
        dtend: "2021-10-04T10:00:00",
        location: "online",
        projects: "+newProject",
        contexts: "@work",
    },
};

export default sampleEvents;